### ISSUE TITLE
CRD Conversion Webhooks

### ISSUE THREAD

**Issue by davidmdm** [yokecd/yoke#38]
Currently, there's an issue with the Airway definition. It allows you to store a map of WebAssembly (Wasm) implementations per version:

```yaml
kind: Airway
spec:
  wasmUrls:
    v1: ...
    v2: ...
```

However, since there can only be one storage version, this functionality is not particularly useful. Only a single implementation of the Airway can exist for the specific storage version.

To facilitate updates between different versions of a Custom Resource Definition (CRD) spec, it would be beneficial if users could specify a conversion webhook Wasm URL.

The ATC would need to spin up a webhook server that accepts requests, matches them to Airway resources, and invokes the appropriate Wasm module to generate the conversion response.

This approach would provide users with an easy way to update their CRDs across versions without requiring them to deploy and manage their own conversion webhook servers.

Since the Airway CRD embeds the CRD spec, an Airway can still specify a different conversion webhook. However, if a conversion webhook is defined at the Airway level, it would take precedence and override any embedded conversion webhook.

This change necessitates a breaking update to the Airway spec. One potential approach could look like this:

```yaml
spec:
  wasm:
    flight: <flight-url>
    converter: <converter-url>
  template:
    # CRD values
    conversion: # Overridden if spec.wasm.converter is specified
```
